### ISSUE TITLE
是否可以考虑添加一个自带的浏览器内核

### ISSUE THREAD

**Issue by logic10492** [qly5213/kcanotify_h5-master#4]
不同安卓手机的webview版本不同 但是却又不方便替换webview 可以自带一个内核吗

**Comment by MerCuJerry** [comment]
其实现在对于Webview的兼容问题也就是不支持75版以上的Webview，一般国内的安卓不折腾是不会有这么高级别的Webview的。另外自带Webview的话会使包体变得臃肿，也不太好
